## 这100道练习，带你玩转Numpy

In [2]:
import numpy as np

In [3]:
np.__version__ 

'1.14.3'

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
v1 = np.zeros(10)
v1[4] = 1
v1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr = np.array([1,2,0,0,4,0])
[i for i in range(len(arr)) if int(arr[i]) != 0 ]

[0, 1, 4]

In [29]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

nonzero 更直接

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.randn(27).reshape(3,3,3) #更简洁的写法 np.random.randn((3,3,3))

array([[[ 1.2016197 , -0.04438386, -0.84162221],
        [ 0.47699674, -0.86262864, -1.22125379],
        [-1.21804633,  0.58053736, -1.82707452]],

       [[ 0.54823395, -0.71139911, -0.80329413],
        [-0.62852226,  0.26274385,  0.46310845],
        [-0.29305424,  0.03107417, -0.31430184]],

       [[-1.24729196,  1.21842736, -0.38346615],
        [-0.17038662,  1.06815745, -0.52041542],
        [-0.23128766,  0.21238888,  0.56639941]]])

In [39]:
arr = np.random.random((10,10))
arr.min(),arr.max()

(0.005616564448622685, 0.9942622210686155)

In [41]:
arr = np.random.random(30)
arr.mean()

0.6028645573874816

In [43]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [47]:
0 * np.nan,np.nan == np.nan,np.inf > np.nan,np.nan - np.nan,0.3 == 3 * 0.1

(nan, False, False, nan, False)

In [48]:
arr = np.diag(1+np.arange(4),k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [49]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [50]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [59]:
arr = np.arange(24).reshape(2,3,4)
np.unravel_index(0,(2,3,4)),np.unravel_index(12,(2,3,4)),np.unravel_index(23,(2,3,4))

((0, 0, 0), (1, 0, 0), (1, 2, 3))

In [63]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [62]:
print(arr[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
arr[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
arr[0][0]

array([0, 1, 2, 3])

In [69]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

感觉array的空间图形出来了...

In [70]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [72]:
arr = np.random.random((5,5))
arrMax, arrMin = arr.max(), arr.min()
z = (arr - arrMin)/(arrMax - arrMin)
z

array([[0.08318772, 0.        , 0.38957134, 0.23409766, 0.80796341],
       [0.55151902, 0.78331514, 0.45082384, 0.89290427, 0.18799472],
       [0.80153455, 0.14361055, 0.49414381, 0.07933882, 0.14569523],
       [0.09259934, 0.33680761, 1.        , 0.93416928, 0.59825302],
       [0.97606681, 0.30332348, 0.65048944, 0.07814397, 0.56156783]])

In [73]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [74]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [75]:
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [76]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) #这里涉及到的是python自带的sum和numpy中的sum不同的用法，也算是sum方法的重载了。
#在py本地库里面sum中接受的第一个值是可迭代的对象，第二个值是最后再相加的值或者迭代器；sum(iterable, start)=可迭代的所有相加和+start值
#而numpy中的sum的第二个元素-1则是代表着最高维度下的相加

9
10


In [78]:
print(sum(np.arange(6).reshape((2,3)),-1))

[ 3 12]


In [79]:
print(sum(np.arange(6).reshape((2,3)),0)) #按照列

[3 5 7]


In [80]:
print(sum(np.arange(6).reshape((2,3)),1)) #按照行

[ 3 12]
